"""
Django settings for SYDrug project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os.path
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2+8_obq$+z$)ws50rvmux3mde(er=*rm9xrpcv2hwy9(fuun3^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1', '43.142.179.249', '*']

# Application definition

INSTALLED_APPS = [
    'simpleui', # 后台美化
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 下方内容pycharm未找到路径，实际上路径已修改配置文件至正确，无碍
    'haystack',
    'apps.user',  # 用户模块
    'apps.goods',  # 商品模块
    'apps.cart',  # 购物车模块
    'tinymce',  # 富文本编辑器
    'apps.order',  # 订单模块


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SYDrug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SYDrug.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SYDrug',
        'USER': 'chenglong',
        'PASSWORD': '123456',
        'host': '43.142.179.249',
        # 'host': '192.168.124.10',
        'PORT': 3306,

    }
}
# django认证系统使用的模型类
AUTH_USER_MODEL = 'user.User'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 富文本编辑器的配置
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400,
}

# 邮件发送的配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 指定邮件后端
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25  # 端口号固定为25
EMAIL_HOST_USER = '3148508410@qq.com'  # 发件人
EMAIL_HOST_PASSWORD = 'zpgytzcyvrnddhfd'  # qq邮箱授权码
EMAIL_USE_TLS = False
EMAIL_FROM = '拾忆医药<3148508410@qq.com>'  # 收件人看到的发件人

# 作为 cache backend 使用配置，将session存储至redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 自己：
        "LOCATION": "redis://43.142.179.249:6379/9",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django 默认可以使用任何 cache backend 作为 session backend, 将 django-redis 作为 session 储存后端不用安装任何额外的 backend
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 配置登录URL地址
LOGIN_URL = "/user/login"

# 设置Django的文件存储类
DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'

# 设置fdfs使用的client.conf文件路径
# FDFS_CLIENT_CONF = '/home/chenglong/SYDrug/utils/fdfs'
FDFS_CLIENT_CONF = '/etc/fdfs/client.conf'

# 设置fdfs存储服务器上nginx的IP和端口号
FDFS_URL = 'http://43.142.179.249:8888/'

# 全文检索框架的配置
HAYSTACK_CONNECTIONS = {
    'default': {
        # 使用whoosh引擎
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        #'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',
        # 索引文件路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),

    }
}

# 当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# 指定搜索结果每页显示的条数
HAYSTACK_SEARCH_RESULTS_PER_PAGE=1

# 支付宝沙箱密钥
app_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDb63NXd2yCPcebx0tRcvPp2pqccGO43U6NWYG/fbytf8U5MUz8BVTXY6FTg78TxLZ+T3RFNHEOkltBrz7e9O2EBRAo0yV6eqn0TXALiZA7AYhZG0LoB/XCIRHaDLvFI0/WXuf86XvHB6oxcFlQTm9Z/4Vi+0lB1MB2DXh5uzM0LyYRno6tFfXjkxQNNw0m5DJvIcsbbOTo2A0Jvhh/5+PhkigD06VY3C6xp/V8dqoOjtg/nRctwN5fXUvpx0uIA+DJbZi0pqS2uVdcYs7lXQlvFsUU8UQeE2rEJIQ9kO65UWsvEgltFVezSboc7lgkQ2kofD4AVe71OEgTn2xGRt2FAgMBAAECggEAf7I5qSIZCY8h5lxUaZjb9IAQoqHH5cHrKLw+UJiMBBpaxJjR4MyftOmO9VVcj/f7F2C/XKfUtedZwcwmL4P8nlnqRipEatfq84Y7dxeLfhenukXQFbb5hp15Jimaph+Y7hrxjbNtQeY7drWLxsukcJekNhM/OFB26JVtzRFb7AIY8bKD1t+sHmMxwKXx7oz0kn2hd0iYVcyA+1JMQuJD6VGVN2cNKo3yZvXJI/W/p+6GhLpxG1f2FpwHw8Xprq8mzTQ5tdNhuBb5AWl98lf8JHSzKLNCNvT4T4SseZjjwKyVw1CkPw6KT083+Ypoxy9e0uUEF9qTGp+jqYI7f7x1SQKBgQDy/CSmRlGCh2Dzqj2geOSHlSXNLU/N3L8cXT3EKNFUAs5LFty3R8OlMg/J4e2X87RVwBzqfNfvkxTb64VIU6/eVpNceMCGH7Y3zEzcNYaw3Jn7NU7QxfV5JzfwUZauJDEx6eQ8UBaEHApxpRcyDLC4R9BhrPW+PK9OILrhZRpljwKBgQDnswhlD+UBBdlaM7JvMT30WBRDpUG6uCmGPGcXbGWI8aG9FeQ82/8kU9NQ39/QnDfM+V2cZG1NeVJBvNt+DdQ8KpTDYn4h2XWrB79ODtO0o4rMH+CXTor1JfPGq6tD0IaHfujj0CogqNlURrA1imge4V8+Y+FHyZBETfDEEz0JqwKBgQDKuV+CcmyS8IwM/14HQpW4ING3CzTn1mKEMa7UuBFdfDHNKDfhmjg63TebAaoO+r7cRDpb0Oj/8sCWcztyCpBSefzcS8qknFSU3RjLKMVFTegSVHl7aY3SFMxw7kE+7Oc2c6N+RntioVp9UnW1xiyyswfCVmF45HyGPHxujMGnNQKBgQCSG3zMtgQz6+tPDVCU+5lU7wIAUkKrqxxMUOS1iZ5RiAX1BcwCcLxovQ+BbVtm4kvxzsIwL8gZVcsAN0a2K6RNOJDM0Nw3HjksW9tQLttjismoxOVMpLPNuVwLSQ/b2LAs22Oi3Q7jv3YkxdqyOJBGANqdrkBOk5WM7RVJn9QatwKBgQCaLhBfeTnECSeys6otT3urpMzL/p84Yn7DHeaq9r2utgwln2RQJO1aa06fEB6FjquCgjYy9roTSfsdEruuRZrBKMaEXUetb+nKKC41AfVVhW+pySAyxRLGOYOcMRc//6iHCk5lypRRgPpzFDv9AsG6CS87/y/cI9qY7DpB8QQwLA==
-----END RSA PRIVATE KEY-----"""

alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoAWmK//pDxa2qgHut4SDzhuxPRGGZt4ze5w6beNAk5m4UU3Yh7Y65FqGE+1hvon3edzWEVgU+KJk+XijWUin9Rs18HtWGbkp0EVvr6fZWbgqHVEjQuchnGl1LuSgTjIfMO5Gy8L4XTamfc9hCy13FPPQLKWkJFVHmcDFe8KI9Q1jrA3D410vb+6xAQM259wv7khoztxHibO3sqsNGQwrx/OqEgGvOk1LkoigJWiCPwIas4wxX7x2ZsPerM6OJsg4576JY+h0C1NTqNa85Mu/jbW/cz3bjOF3BtHKt9am0XAmjwOrr9+Eq+GrBJIB4+JZts0/UzQJRX6lmlpFLQlhJQIDAQAB
-----END PUBLIC KEY-----"""


alipay_account = 'ldlqux8986@sandbox.com'

STATIC_ROOT=os.path.join(BASE_DIR, "staticfiles")
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
#SIMPLEUI_LOGO = 'http://43.142.179.249:8888/group1/M00/00/00/CgAEBWQzc7WAUKZWAAAR1q-NIEY354.png'

# 隐藏首页的快捷操作和最近动作
#SIMPLEUI_HOME_QUICK = False
#SIMPLEUI_HOME_ACTION = False

# 修改左侧菜单首页设置
#SIMPLEUI_HOME_PAGE = 'https://www.baidu.com/'  # 指向页面
SIMPLEUI_HOME_TITLE = '拾忆医药欢迎您!' # 首页标题
SIMPLEUI_HOME_ICON = 'fa fa-code' # 首页图标

# 设置右上角Home图标跳转链接，会以另外一个窗口打开
#SIMPLEUI_INDEX = 'https://www.baidu.com/'
