# Generated by Django 3.1 on 2023-04-07 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230406_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='订单id'),
        ),
    ]
