# Generated by Django 3.1 on 2023-04-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20230320_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goods', verbose_name='商品SPU'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodstype', verbose_name='商品种类'),
        ),
    ]
